### PR TITLE
Ground up test

### PR DESCRIPTION
**Pull request by dgl888**
What? 
I refactored a lot of code to be more modular.  I reduced the size of the update method, moving a lot of the functionality into other modules. I also fixed the collision detection to be spot on. Beforehand, the ball would clip out of the total width/height, which looked weird. I also updated the ball speed so that it would be random on start, but would not be bugged anymore. Lastly, I made it where the ball would initialize to any direction, not just bottom right. To make the game more interesting, I changed the look of the game to better looking, and also added a sound effect to the ball when it bounces.
Why?
I wanted to update the function to have less lines in the index file. Also, I believe these minor bugs would be bothersome if focused on.

https://user-images.githubusercontent.com/44234631/174494442-f1963eb6-c425-4f10-afdf-dd41008c0b3c.mp4

```
1. Make sure you don't have more than 10 lines for a single function. Writing comments everywhere is bad design. A good clean code can be understood by an english reader without comments. Clean up your code.
2. Ball speed has bugs, fix that
3. Game is boring make it more exciting. Feel free to add, change a mechanic to make it more fun.```

### CODE REVIEW

**Comment by demiculus** [comment]
Why does all commits start with Groundup ?
I'll review after you put a video showcasing the changes to the PR description.

**Comment by dgl888** [comment]
@demiculus For the team I currently work on, we always head our commits with the branch name. So I am just used to having some sort of branch name as the title of my commit. I will get you that video later this afternoon.

**Comment by dgl888** [comment]
@demiculus I have put the video on the description. I am currently on the vacation in the mountains, so I have pretty spotty internet. Please let me know if you were able to see the properly uploaded video.

I was having issues with my screen recorder that is on my laptop; the recorder did not want to record either the console, or the audio. So I am sending you a video of the one with audio, since that I actually changed. Let me know if you would like to see the console, it is the same as before.

**Comment by dgl888** [comment]
@demiculus I am currently working on adding a powerup method that should spice the game up a little bit. I have the powerup being setup and activated/deactivated properly. I am going to work tomorrow on adding what the powerup will do. I am planning on including this in the next PR once you review this one. Thanks!

**Pull request closed without merging**
